title: Zhengxian He
description: Zhengxian He's Homepage

url: http://brianmaierjr.github.com/long-haul
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: kramdown
highlighter: rouge
gems: [jekyll-paginate]
paginate: 5

navigation:
 - title: Home
   url: /index.html
 - title: About
   url: /about
 - title: Contact
   url: /contact

social:
   github: SeanHzx

   facebook: brianmaierjr
   email: zhe72@gatech.edu

google_analytics: "UA-88959514-2"
