highlighter: rouge
markdown: kramdown
rdiscount:
  extensions: [smart]
permalink: :title.html
paginate: 5
plugins: [jekyll-paginate]
port: 4000
safe: true
url: http://biomadeira.github.io/vitae
author: Fábio Madeira

# edit this section with your information
# biomadeira.github.io - all contents run on /vitae/
# for a normal use at the base of the server change it to "/"
baseurl: /
title: Zhengxian He's Homepage
name: Zhengxian He
email: zhe72@gatech.edu
email_full: mailto:zhe72@gatech.edu
website: seanhzx.github.io
website_full: https://seanhzx.github.io
github: SeanHzx
tel: +1 470-439-1829
tel_full: tel:+14704391829
google_maps: 'https://www.google.com/maps/place/Klaus+Advanced+Computing+Building/@33.7772559,-84.3983733,17z/data=!3m1!4b1!4m5!3m4!1s0x87b781ec0ab42ea5:0x16eec927f37b40ec!8m2!3d33.7772515!4d-84.3961846'
address: Klaus Advanced Computing Building Room 208,
postcode: 266 Ferst Dr NW, 30332
city: Atlanta, GA,
country: United States
google_analytics: UA-88959514-2

# needed for travis-ci build
exclude: [vendor]
